FROM oven/bun:1.3.9-alpine AS build

WORKDIR /app

ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ARG NEXT_PUBLIC_GOOGLE_FEATURABLE_WIDGET
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST

ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ENV NEXT_PUBLIC_GOOGLE_FEATURABLE_WIDGET=$NEXT_PUBLIC_GOOGLE_FEATURABLE_WIDGET
ENV NEXT_PUBLIC_POSTHOG_KEY=$NEXT_PUBLIC_POSTHOG_KEY
ENV NEXT_PUBLIC_POSTHOG_HOST=$NEXT_PUBLIC_POSTHOG_HOST

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

FROM caddy:2.10-alpine

COPY --from=build /app/dist /srv
COPY deploy/Caddyfile.vite /etc/caddy/Caddyfile

EXPOSE 80
